# Generated by Django 4.1 on 2022-09-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPrestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestamos',
            new_name='Prestamo',
        ),
    ]
