# Generated by Django 4.1 on 2022-09-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPrestamos', '0004_devolution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devolution',
            new_name='Devolucion',
        ),
    ]
